"""Add delegation table

Revision ID: d00825f2a89a
Revises: fix_session_constraints
Create Date: 2025-04-20 07:57:56.365962+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd00825f2a89a'
down_revision: Union[str, None] = 'fix_session_constraints'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_automation_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('session_duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_automation_settings_id'), 'user_automation_settings', ['id'], unique=False)
    # op.drop_index('ix_delegations_delegate_address', table_name='delegations') # Commented out: Index doesn't exist / Table drop handles this
    # op.drop_index('ix_delegations_id', table_name='delegations')                 # Commented out: Index doesn't exist / Table drop handles this
    # op.drop_index('ix_delegations_is_active', table_name='delegations')          # Commented out: Index doesn't exist / Table drop handles this
    # op.drop_index('ix_delegations_user_id', table_name='delegations')           # Commented out: Index doesn't exist / Table drop handles this
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delegations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('delegate_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('signed_delegation_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='delegations_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='delegations_pkey')
    )
    op.create_index('ix_delegations_user_id', 'delegations', ['user_id'], unique=False)
    op.create_index('ix_delegations_is_active', 'delegations', ['is_active'], unique=False)
    op.create_index('ix_delegations_id', 'delegations', ['id'], unique=False)
    op.create_index('ix_delegations_delegate_address', 'delegations', ['delegate_address'], unique=False)
    op.drop_index(op.f('ix_user_automation_settings_id'), table_name='user_automation_settings')
    op.drop_table('user_automation_settings')
    # ### end Alembic commands ### 