"""consolidate_session_model

Revision ID: 881e615d25ac
Revises: d00825f2a89a
Create Date: 2025-04-28 15:55:31.429652+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '881e615d25ac'
down_revision: Union[str, None] = 'd00825f2a89a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delegations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delegate_address', sa.String(), nullable=False),
    sa.Column('signed_delegation_data', sa.TEXT(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delegations_delegate_address'), 'delegations', ['delegate_address'], unique=False)
    op.create_index(op.f('ix_delegations_id'), 'delegations', ['id'], unique=False)
    op.create_index(op.f('ix_delegations_is_active'), 'delegations', ['is_active'], unique=False)
    op.create_index(op.f('ix_delegations_user_id'), 'delegations', ['user_id'], unique=False)
    
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_api_key_id'), 'sessions', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_sessions_is_active'), 'sessions', ['is_active'], unique=False)
    
    # Create index with a different name
    op.create_index('sessions_active_api_key_unique', 'sessions', ['api_key_id', 'is_active'], unique=True, postgresql_where=sa.text('is_active IS true'))
    
    # Drop old user_sessions table
    op.drop_index('ix_user_sessions_id', table_name='user_sessions')
    op.drop_index('ix_user_sessions_session_id', table_name='user_sessions')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], name='user_sessions_api_key_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_sessions_pkey')
    )
    op.create_index('unique_active_api_key_session', 'user_sessions', ['api_key_id'], unique=True, postgresql_where='(is_active = true)')
    op.create_index('ix_user_sessions_session_id', 'user_sessions', ['session_id'], unique=False)
    op.create_index('ix_user_sessions_id', 'user_sessions', ['id'], unique=False)
    
    # Drop the sessions table and its indices
    op.drop_index('sessions_active_api_key_unique', table_name='sessions')
    op.drop_index(op.f('ix_sessions_is_active'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_api_key_id'), table_name='sessions')
    op.drop_table('sessions')
    
    # Drop the delegations table and its indices
    op.drop_index(op.f('ix_delegations_user_id'), table_name='delegations')
    op.drop_index(op.f('ix_delegations_is_active'), table_name='delegations')
    op.drop_index(op.f('ix_delegations_id'), table_name='delegations')
    op.drop_index(op.f('ix_delegations_delegate_address'), table_name='delegations')
    op.drop_table('delegations')
    # ### end Alembic commands ### 